name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.9
          
      - name: Run a one-line script
        run: echo Hello.
        
      - name: Create and start virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
      
      - name: Install spim
        run: sudo apt-get update -qq && sudo apt-get install -y -qq spim
        
      - name: Test!
        run: ./run.sh
          
